# Speed Test:

In [10]:
import numpy as np
import time
import sys

In [2]:
size: int = 1_000_000_00

In [4]:
# Python List:
list_1: list[int] = list(range(size))
list_2: list[int] = list(range(size))

start: float = time.time()
result: list[int] = [x + y for x, y in zip(list_1, list_2)]
end: float = time.time()

print(f'Python list addition time => {end-start}')

Python list addition time => 14.526472091674805


In [3]:

# Numpy Arrays:
arr_1 = np.array(list(range(size)))
arr_2 = np.array(list(range(size)))

start: float = time.time()
result = arr_1 + arr_2 # Vectorized Operation
end: float = time.time()

print(f'Numpy arrays addition time => {end-start}')

Numpy arrays addition time => 0.43528294563293457


# Numpy Arrays:

In [3]:
np.array([1,2,3,4,5,'Anurag'])

array(['1', '2', '3', '4', '5', 'Anurag'], dtype='<U21')

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array([[1,2,3],[4,5,6]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(2, 3)

# Memory Efficiency

In [11]:
list_data: list[int] = list(range(1000))
numpy_data = np.array(list_data)
print(f'Python list size: {sys.getsizeof(list_data) * len(list_data)} bytes.')
print(f'Numpy array size: {numpy_data.nbytes} bytes.')

Python list size: 8056000 bytes.
Numpy array size: 8000 bytes.


In [12]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

# Speed Test:

In [16]:
# Python List:
lst: list[int] = list(range(1000_000_0))
start: float = time.time()
lst_sqr: list[int] = [i ** 2 for i in lst]
end: float = time.time()
print(f'Python list squaring time => {end-start}')

Python list squaring time => 1.064993143081665


In [17]:
# Numpy Arrays:
arr = np.array(list(range(1000_000_0)))
start: float = time.time()
lst_sqr: arr = arr ** 2
end: float = time.time()
print(f'Numpy array squaring time => {end-start}')

Numpy array squaring time => 0.205855131149292
