# Speed Test:

In [18]:
import numpy as np
import time
import sys

In [19]:
size: int = 1_000_000_00

In [20]:
# Python List:
list_1: list[int] = list(range(size))
list_2: list[int] = list(range(size))

start: float = time.time()
result: list[int] = [x + y for x, y in zip(list_1, list_2)]
end: float = time.time()

print(f'Python list addition time => {end-start}')

Python list addition time => 14.379233121871948


In [21]:
# Numpy Arrays:
arr_1 = np.array(list(range(size)))
arr_2 = np.array(list(range(size)))

start: float = time.time()
result = arr_1 + arr_2 # Vectorized Operation
end: float = time.time()

print(f'Numpy arrays addition time => {end-start}')

Numpy arrays addition time => 6.25150990486145


# Numpy Arrays:

In [22]:
np.array([1,2,3,4,5,'Anurag'])

array(['1', '2', '3', '4', '5', 'Anurag'], dtype='<U21')

In [23]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [24]:
arr = np.array([[1,2,3],[4,5,6]])

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr.shape

(2, 3)

# Memory Efficiency

In [28]:
list_data: list[int] = list(range(1000))
numpy_data = np.array(list_data)
print(f'Python list size: {sys.getsizeof(list_data) * len(list_data)} bytes.')
print(f'Numpy array size: {numpy_data.nbytes} bytes.')

Python list size: 8056000 bytes.
Numpy array size: 8000 bytes.


In [13]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

# Speed Test:

In [14]:
# Python List:
lst: list[int] = list(range(1000_000_0))
start: float = time.time()
lst_sqr: list[int] = [i ** 2 for i in lst]
end: float = time.time()
print(f'Python list squaring time => {end-start}')

Python list squaring time => 0.39551305770874023


In [15]:
# Numpy Arrays:
arr = np.array(list(range(1000_000_0)))
start: float = time.time()
lst_sqr: arr = arr ** 2
end: float = time.time()
print(f'Numpy array squaring time => {end-start}')

Numpy array squaring time => 0.17467498779296875
