In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flat = arr.flatten()
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[0]

np.int64(1)

In [7]:
flat[0:4]

array([1, 2, 3, 4])

In [ ]:
flat[:3] # Get first 3

array([1, 2, 3])

In [ ]:
flat[3:] # Get all from 3rd index to last element

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [12]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [14]:
b[0] = 4444
b

array([4444,    5,    6,    7])

In [15]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [16]:
b = np.copy(flat)
b

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [17]:
b[0] = 1234
b

array([1234,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [18]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [19]:
arr = np.array([1,4,23,5,52,646,4,54])
arr

array([  1,   4,  23,   5,  52, 646,   4,  54])

In [21]:
arr[[1,2,4]] # Facncy Indexing

array([ 4, 23, 52])

In [ ]:
arr[arr>4] # Boolean Masking

array([ 23,   5,  52, 646,  54])

In [23]:
np.array([[1,2,3],[6,7,8],[11,12,13]]).shape

(3, 3)

In [24]:
np.array([1.5,2.66,9.8]).astype('int64')

array([1, 2, 9])

In [25]:
a1 = np.array([1,2,3,4,5,6])
a1[a1%2==0]

array([2, 4, 6])

In [26]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
a1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a2 = np.array([1,4,23,5,52,646,4,54])
a2[a2>50]

array([ 52, 646,  54])