In [1]:
import numpy as np

In [2]:
arr = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [4]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [8]:
arr[0][1]

np.int64(2)

In [9]:
arr[0,1]

np.int64(2)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [13]:
arr3d = np.array(
    [[[1,2,3],
      [4,5,6]],
     
     [[7,8,9],
      [10,11,12]]]
)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr3d.shape

(2, 2, 3)

In [15]:
arr3d.ndim

3

In [16]:
arr3d[0,1,2]

np.int64(6)

In [17]:
arr3d[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])