In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
result = arr + 10
result

array([11, 12, 13, 14, 15])

In [ ]:
result # It is brodcasted no extra memory is used here

array([11, 12, 13, 14, 15])

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
arr1 + arr2

array([[2, 4, 6],
       [5, 7, 9]])

In [7]:
data = np.array(
    [[10,20,30],
     [15,25,35],
     [20,30,40],
     [25,35,45],
     [30,40,50]
    ])
mean = data.mean(axis=0)
std = data.std(axis=0)

normalised_data = (data-mean)/std
print(normalised_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
