In [26]:
import numpy as np

In [27]:
arr = np.array([3,2,6,3,21,44])
arr

array([ 3,  2,  6,  3, 21, 44])

In [28]:
np.mean(arr)

np.float64(13.166666666666666)

In [29]:
np.min(arr)

np.int64(2)

In [30]:
np.max(arr)

np.int64(44)

In [31]:
np.std(arr)

np.float64(15.247039785552547)

In [32]:
np.var(arr)

np.float64(232.47222222222226)

In [33]:
np.sum(arr)

np.int64(79)

In [34]:
np.prod(arr)

np.int64(99792)

In [35]:
np.percentile(arr, 50)

np.float64(4.5)

In [36]:
np.argmax(arr)

np.int64(5)

In [37]:
np.argmin(arr)

np.int64(1)

In [38]:
np.unique(arr)

array([ 2,  3,  6, 21, 44])

In [39]:
np.cumsum(arr)

array([ 3,  5, 11, 14, 35, 79])